/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Architecture } from "./Architecture";
import { ArchitectureCountArgs } from "./ArchitectureCountArgs";
import { ArchitectureFindManyArgs } from "./ArchitectureFindManyArgs";
import { ArchitectureFindUniqueArgs } from "./ArchitectureFindUniqueArgs";
import { DeleteArchitectureArgs } from "./DeleteArchitectureArgs";
import { ArchitectureService } from "../architecture.service";
@graphql.Resolver(() => Architecture)
export class ArchitectureResolverBase {
  constructor(protected readonly service: ArchitectureService) {}

  async _architecturesMeta(
    @graphql.Args() args: ArchitectureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Architecture])
  async architectures(
    @graphql.Args() args: ArchitectureFindManyArgs
  ): Promise<Architecture[]> {
    return this.service.architectures(args);
  }

  @graphql.Query(() => Architecture, { nullable: true })
  async architecture(
    @graphql.Args() args: ArchitectureFindUniqueArgs
  ): Promise<Architecture | null> {
    const result = await this.service.architecture(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Architecture)
  async deleteArchitecture(
    @graphql.Args() args: DeleteArchitectureArgs
  ): Promise<Architecture | null> {
    try {
      return await this.service.deleteArchitecture(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
