/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Hardware } from "./Hardware";
import { HardwareCountArgs } from "./HardwareCountArgs";
import { HardwareFindManyArgs } from "./HardwareFindManyArgs";
import { HardwareFindUniqueArgs } from "./HardwareFindUniqueArgs";
import { DeleteHardwareArgs } from "./DeleteHardwareArgs";
import { HardwareService } from "../hardware.service";
@graphql.Resolver(() => Hardware)
export class HardwareResolverBase {
  constructor(protected readonly service: HardwareService) {}

  async _hardwareItemsMeta(
    @graphql.Args() args: HardwareCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Hardware])
  async hardwareItems(
    @graphql.Args() args: HardwareFindManyArgs
  ): Promise<Hardware[]> {
    return this.service.hardwareItems(args);
  }

  @graphql.Query(() => Hardware, { nullable: true })
  async hardware(
    @graphql.Args() args: HardwareFindUniqueArgs
  ): Promise<Hardware | null> {
    const result = await this.service.hardware(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Hardware)
  async deleteHardware(
    @graphql.Args() args: DeleteHardwareArgs
  ): Promise<Hardware | null> {
    try {
      return await this.service.deleteHardware(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
