/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AdditionalSettings } from "./AdditionalSettings";
import { AdditionalSettingsCountArgs } from "./AdditionalSettingsCountArgs";
import { AdditionalSettingsFindManyArgs } from "./AdditionalSettingsFindManyArgs";
import { AdditionalSettingsFindUniqueArgs } from "./AdditionalSettingsFindUniqueArgs";
import { DeleteAdditionalSettingsArgs } from "./DeleteAdditionalSettingsArgs";
import { AdditionalSettingsService } from "../additionalSettings.service";
@graphql.Resolver(() => AdditionalSettings)
export class AdditionalSettingsResolverBase {
  constructor(protected readonly service: AdditionalSettingsService) {}

  async _additionalSettingsItemsMeta(
    @graphql.Args() args: AdditionalSettingsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AdditionalSettings])
  async additionalSettingsItems(
    @graphql.Args() args: AdditionalSettingsFindManyArgs
  ): Promise<AdditionalSettings[]> {
    return this.service.additionalSettingsItems(args);
  }

  @graphql.Query(() => AdditionalSettings, { nullable: true })
  async additionalSettings(
    @graphql.Args() args: AdditionalSettingsFindUniqueArgs
  ): Promise<AdditionalSettings | null> {
    const result = await this.service.additionalSettings(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AdditionalSettings)
  async deleteAdditionalSettings(
    @graphql.Args() args: DeleteAdditionalSettingsArgs
  ): Promise<AdditionalSettings | null> {
    try {
      return await this.service.deleteAdditionalSettings(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
